# Generated by `just brew-publish <version>` in slantedt/spec-dag, from
# scripts/brew/spec-tools.rb.tmpl. Do not hand-edit — the next release
# overwrites this file wholesale, and an edit here is lost without a diff.
#
# The binaries come from downloads.slantedt.com rather than from a GitHub
# release asset: slantedt/spec-dag is private and stays private, so an asset
# would put a token in every install path. The bucket, the object layout and
# the publisher that fills it live in slantedt/slantedt-dist.
#
# Every sha256 below was read from the channel's own `.tar.gz.sha256` object at
# publish time, so a formula that pins a checksum is also proof that the
# archive it names was actually reachable.
class SpecTools < Formula
  desc "Graph over a Gherkin spec corpus: validate, find, coverage, claims"
  homepage "https://github.com/slantedt/spec-dag"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://downloads.slantedt.com/spec-tools/0.4.0/spec-tools-0.4.0-macos-arm64.tar.gz"
      sha256 "ea39a7c098f6772d2b553d36c0ef74e2f8bd1836fdaf9158c707d0c32c5950cb"
    end
    on_intel do
      url "https://downloads.slantedt.com/spec-tools/0.4.0/spec-tools-0.4.0-macos-x86_64.tar.gz"
      sha256 "682ab222f83d7419c7b6ec4ffed810c345cccbcdc52cac6c9dba709d29d96b8d"
    end
  end

  on_linux do
    on_intel do
      url "https://downloads.slantedt.com/spec-tools/0.4.0/spec-tools-0.4.0-linux-x86_64.tar.gz"
      sha256 "23fe8afbf922c03b8fc0c103818241a82a5956b9745d49b13d0cd1929620d3b7"
    end
  end

  # One executable at the root of the archive — the shape .github/scripts/package.sh
  # writes and the shape asdf-slantedt's bin/download asserts.
  def install
    bin.install "spec-tools"
  end

  # Installed means runs, and runs as the version this formula claims. Same
  # standard bin/install in asdf-slantedt holds itself to, for the same reason:
  # a binary that copied fine and then will not execute is worth catching here.
  test do
    assert_match "spec-tools #{version}", shell_output("#{bin}/spec-tools --version")
  end
end
