# Generated by `just brew-publish <version>` in slantedt/spec-dag, from
# scripts/brew/spec-tools.rb.tmpl. Do not hand-edit — the next release
# overwrites this file wholesale, and an edit here is lost without a diff.
#
# The binaries come from downloads.slantedt.com rather than from a GitHub
# release asset: slantedt/spec-dag is private and stays private, so an asset
# would put a token in every install path. The bucket, the object layout and
# the publisher that fills it live in slantedt/slantedt-dist.
#
# Every sha256 below was read from the channel's own `.tar.gz.sha256` object at
# publish time, so a formula that pins a checksum is also proof that the
# archive it names was actually reachable.
class SpecTools < Formula
  desc "Graph over a Gherkin spec corpus: validate, find, coverage, claims"
  homepage "https://github.com/slantedt/spec-dag"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://downloads.slantedt.com/spec-tools/0.3.0/spec-tools-0.3.0-macos-arm64.tar.gz"
      sha256 "6e08cb9d6b023150fd6ae6c268c243474f241e8a02149261c7436c69ff97e58a"
    end
    on_intel do
      url "https://downloads.slantedt.com/spec-tools/0.3.0/spec-tools-0.3.0-macos-x86_64.tar.gz"
      sha256 "3f4fcb9ebef6f6384a056e5c30317ad9c14c60e14e54e7b2b7e6da0e68ca3f75"
    end
  end

  on_linux do
    on_intel do
      url "https://downloads.slantedt.com/spec-tools/0.3.0/spec-tools-0.3.0-linux-x86_64.tar.gz"
      sha256 "e9545ed5235eb6446f4db0b946b6fb4dd6552571466f6271a342322d0ec9c8a5"
    end
  end

  # One executable at the root of the archive — the shape .github/scripts/package.sh
  # writes and the shape asdf-slantedt's bin/download asserts.
  def install
    bin.install "spec-tools"
  end

  # Installed means runs, and runs as the version this formula claims. Same
  # standard bin/install in asdf-slantedt holds itself to, for the same reason:
  # a binary that copied fine and then will not execute is worth catching here.
  test do
    assert_match "spec-tools #{version}", shell_output("#{bin}/spec-tools --version")
  end
end
