# Generated by `just brew-publish <version>` in slantedt/spec-dag, from
# scripts/brew/spec-tools.rb.tmpl. Do not hand-edit — the next release
# overwrites this file wholesale, and an edit here is lost without a diff.
#
# The binaries come from downloads.slantedt.com rather than from a GitHub
# release asset: slantedt/spec-dag is private and stays private, so an asset
# would put a token in every install path. The bucket, the object layout and
# the publisher that fills it live in slantedt/slantedt-dist.
#
# Every sha256 below was read from the channel's own `.tar.gz.sha256` object at
# publish time, so a formula that pins a checksum is also proof that the
# archive it names was actually reachable.
class SpecTools < Formula
  desc "Graph over a Gherkin spec corpus: validate, find, coverage, claims"
  homepage "https://github.com/slantedt/spec-dag"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://downloads.slantedt.com/spec-tools/0.7.0/spec-tools-0.7.0-macos-arm64.tar.gz"
      sha256 "fd52828c162adc884cd5a11057ad93836486023090171953a4a7734a8f4f6732"
    end
    on_intel do
      url "https://downloads.slantedt.com/spec-tools/0.7.0/spec-tools-0.7.0-macos-x86_64.tar.gz"
      sha256 "22c927778a2cd970f7b61d3593f619750cf62d9d99478621d6493d12b00486bb"
    end
  end

  on_linux do
    on_intel do
      url "https://downloads.slantedt.com/spec-tools/0.7.0/spec-tools-0.7.0-linux-x86_64.tar.gz"
      sha256 "b8c6629624197ec6197b9e79ccd0b47913c229c9ad6366be6779da08ce254a78"
    end
  end

  # One executable at the root of the archive — the shape .github/scripts/package.sh
  # writes and the shape asdf-slantedt's bin/download asserts.
  def install
    bin.install "spec-tools"
  end

  # Installed means runs, and runs as the version this formula claims. Same
  # standard bin/install in asdf-slantedt holds itself to, for the same reason:
  # a binary that copied fine and then will not execute is worth catching here.
  test do
    assert_match "spec-tools #{version}", shell_output("#{bin}/spec-tools --version")
  end
end
